version: '3.9'

services:
  bulky:
    image: transloadit/companion
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /mnt/bulky-server-data:/mnt/bulky-server-data
    ports:
      - "3020:3020"
    env_file:
     - .env
